<a href="https://colab.research.google.com/github/shkkonda/TransactionClassifier/blob/colab/LazyPay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [23]:
df = pd.read_excel("LazyPay2021_22.xlsx", header=None)

In [24]:
df.head()

                     0
0              LAZYPAY
1  2022-11-01 00:00:00
2                 4064
3           Successful
4               Rapido

In [40]:
new_df = pd.DataFrame({'Name': df[::4].reset_index()[0], 'Date': df[1::4].reset_index()[0], 'Amount': df[2::4].reset_index()[0], 'Status': df[3::4].reset_index()[0]})

In [41]:
new_df.head()

            Name                 Date Amount      Status
0        LAZYPAY  2022-11-01 00:00:00   4064  Successful
1         Rapido  2022-10-21 00:00:00    -79        Paid
2         Rapido  2022-10-21 00:00:00    -79        Paid
3  Urban Company  2022-10-20 00:00:00   -229        Paid
4         Swiggy  2022-10-18 00:00:00   -137        Paid